### PR TITLE
Stop installing multiple copies of the shared library.

### PR DESCRIPTION
**Pull request by bodea**
This is never linked into programs by `ld`, so the symlink redirections from `.so`
and soname are not required.  Moreover, the Debian package was ending up with
three copies of the same file (rather than one file and two symlinks).

The only copy will be installed as `libnss_cache.so.2`, to meet the API for NSS
which expects to load `libnss_<service>.so.<x>`, where _x_ is 2 for glibc 2.1 and
later (see nsswitch.conf(5)).

### CODE REVIEW

**Review by schachmat — APPROVED** [review]

**Review by bbaetz — APPROVED** [review]

**Review by smu-ggl — APPROVED** [review]

**Comment by kev009** [comment]
This might have been too eager, I am fine with just one library but maybe we need to continue using the SONAME variable?

```Warning: /usr/ports/net/libnss-cache/work/stage/usr/local/lib/nss_nsscache.so.1 doesn't have a SONAME.
Warning: pkg(8) will not register it as being provided by the port.
Warning: If another port depend on it, pkg will not be able to know where it comes from.
Warning: It is directly in /usr/local/lib, it is probably used by other ports.```

**Comment by bodea** [comment]
A `SONAME` is only required when linking via a `libnss_cache.so` symlink, so that the linker writes `libnss_cache.so.2` into the binary rather than the path name.  We're not providing such a symlink, so it is not necessary.  If someone were to link to the library for some reason, that would require passing using the full path (rather than using `-lnss_cache`), in which case the linker records that path correctly.

**Comment by kev009** [comment]
> A `SONAME` is only required when linking via a `libnss_cache.so` symlink, so that the linker writes `libnss_cache.so.2` into the binary rather than the path name. We're not providing such a symlink, so it is not necessary. If someone were to link to the library for some reason, that would require passing using the full path (rather than using `-lnss_cache`), in which case the linker records that path correctly.

Empirically it seems to be used by the pkg system.  Can it not be set to the same file name?

**Comment by kev009** [comment]
Who even are the people that approved and merged this with no history with the repo.  Typical abysmal Google engineering quality...

This is a standard Debian lint as well https://lintian.debian.org/tags/sharedobject-in-library-directory-missing-soname.html

**Pull request merged**
